domain: nitro-staging.human-connection.org
commit: 889a7cdd24dda04a139b2b77d626e984d6db6781
pullPolicy: Always

# configs
developmentMailserverDomain: "nitro-mailserver.human-connection.org"
smtpHost: "mailserver.human-connection"
smtpPort: "25"
smtpUsername:
smtpPassword:
sentryDsnWebapp:
sentryDsnBackend:
neo4jResourceRequestsMemory: "1G"
neo4jResourceLimitsMemory: "1G"
neo4jConfig:
  apoc_import_file_enabled: "true"
  dbms_memory_pagecache_size: "490M"
  dbms_memory_heap_max__size: "500M"
  dbms_memory_heap_initial__size: "500M"

# secrets
jwtSecret: b/&&7b78BF&fv/Vd
privateKeyPassphrase: a7dsf78sadg87ad87sfagsadg78
mapboxToken: pk.eyJ1IjoiaHVtYW4tY29ubmVjdGlvbiIsImEiOiJjajl0cnBubGoweTVlM3VwZ2lzNTNud3ZtIn0.KZ8KK9l70omjXbEkkbHGsQ
mongodbUsername:
mongodbPassword:
neo4jUsername: neo4j
neo4jPassword: neo4j
