apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Release.Name }}-maintenance
  namespace: human-connection
spec:
  selector:
    matchLabels:
      human-connection.org/selector: deployment-maintenance
  template:
    metadata:
      labels:
        human-connection.org/commit: {{ .Values.commit }}
        human-connection.org/selector: deployment-maintenance
      name: maintenance
    spec:
      containers:
        - name: maintenance
          env:
            - name: HOST
              value: 0.0.0.0
          image: humanconnection/maintenance:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
