apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Release.Name }}-backend
  namespace: human-connection
spec:
  replicas: 1
  minReadySeconds: 15
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: "100%"
  selector:
    matchLabels:
      human-connection.org/selector: deployment-backend
  template:
    metadata:
      name: deployment-backend
      annotations:
        backup.velero.io/backup-volumes: uploads
      labels:
        human-connection.org/commit: {{ .Values.commit }}
        human-connection.org/selector: deployment-backend
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-configmap
        - secretRef:
            name: {{ .Release.Name }}-secrets
        image: humanconnection/nitro-backend:latest
        imagePullPolicy: {{ .Values.pullPolicy }}
        name: backend
        ports:
        - containerPort: 4000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /nitro-backend/public/uploads
            name: uploads
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: uploads-claim
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
status: {}
