apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name:  {{ .Release.Name }}-ingress
  namespace: human-connection
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: {{ .Values.letsencryptIssuer }}
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  tls:
    - hosts:
      - {{ .Values.humanConnectionDomain }}
      secretName: tls
  rules:
    - host: {{ .Values.humanConnectionDomain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-webapp
              servicePort: 3000
{{- if .Values.developmentMailserverDomain }}
    - host: {{ .Values.developmentMailserverDomain }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-mailserver
            servicePort: 80
{{- end }}
