---
  apiVersion: v1
  kind: ConfigMap
  data:
    GRAPHQL_PORT: "4000"
    GRAPHQL_URI: "http://nitro-backend.human-connection:4000"
    MOCK: "false"
    NEO4J_URI: "bolt://nitro-neo4j.human-connection:7687"
    NEO4J_USER: "neo4j"
    NEO4J_AUTH: "none"
    CLIENT_URI: "https://nitro-staging.human-connection.org"
    MAPBOX_TOKEN: "pk.eyJ1IjoiaHVtYW4tY29ubmVjdGlvbiIsImEiOiJjajl0cnBubGoweTVlM3VwZ2lzNTNud3ZtIn0.KZ8KK9l70omjXbEkkbHGsQ"
  metadata:
    name: configmap
    namespace: human-connection
