dist: xenial
language: generic
addons:
  apt:
    packages:
      - libgconf-2-4
  snaps:
    - 'doctl --classic'
    - docker
    - chromium
    - 'kubectl --classic'

before_install:
  - yarn global add wait-on
  - yarn install
  - cp cypress.env.template.json cypress.env.json

install:
  - docker-compose -f docker-compose.yml -f docker-compose.travis.yml up --build -d
  - wait-on http://localhost:7474 && docker-compose exec neo4j migrate

script:
  - docker-compose exec backend yarn run lint
  - docker-compose exec backend yarn run test:jest --ci --verbose=false
  - docker-compose exec backend yarn run db:reset
  - docker-compose exec backend yarn run db:seed
  - docker-compose exec backend yarn run test:cucumber
  - docker-compose exec backend yarn run db:reset
  - docker-compose exec backend yarn run db:seed
  - docker-compose exec webapp yarn run lint
  - docker-compose exec webapp yarn run test --ci --verbose=false
  - docker-compose exec -d backend yarn run test:before:seeder
  - yarn run cypress:run --record --key $CYPRESS_TOKEN

after_success:
  - doctl auth init --access-token $DOCTL_ACCESS_TOKEN
  - mkdir -p ~/.kube/
  - doctl kubernetes cluster kubeconfig show nitro-staging > ~/.kube/config.yaml
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
  - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_EVENT_TYPE == "push" ]; then
    wget https://raw.githubusercontent.com/Human-Connection/Discord-Bot/develop/tester.sh &&
    chmod +x tester.sh &&
    ./tester.sh staging $WEBHOOK_URL;
    fi

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

deploy:
  - provider: script
    script: scripts/docker_push.sh
    on:
      branch: master
  - provider: script
    script: scripts/deploy.sh
    on:
      branch: master
