version: '3.7'

services:
  webapp:
    build:
      context: .
      target: build-and-test
    volumes:
      - .:/nitro-web
      - node_modules:/nitro-web/node_modules
    command: yarn run dev

volumes:
  node_modules:
