version: "3.4"

services:
  backend:
    volumes:
      - uploads:/nitro-backend/public/uploads
  neo4j:
    volumes:
      - mongo-export:/mongo-export
    environment:
      - NEO4J_apoc_import_file_enabled=true
  maintenance:
    build:
      context: maintenance
    volumes:
      - mongo-export:/mongo-export
      - uploads:/uploads
      - ./maintenance/migration/:/migration
      - ./maintenance/.ssh/:/root/.ssh/
    networks:
      - hc-network
    depends_on:
      - backend
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - "SSH_USERNAME=${SSH_USERNAME}"
      - "SSH_HOST=${SSH_HOST}"
      - "MONGODB_USERNAME=${MONGODB_USERNAME}"
      - "MONGODB_PASSWORD=${MONGODB_PASSWORD}"
      - "MONGODB_AUTH_DB=${MONGODB_AUTH_DB}"
      - "MONGODB_DATABASE=${MONGODB_DATABASE}"
      - "UPLOADS_DIRECTORY=${UPLOADS_DIRECTORY}"

volumes:
  mongo-export:
  uploads:
