version: '3.7'

services:
  webapp:
    image: humanconnection/nitro-web:latest
    build:
      context: .
      target: production
    ports:
      - 3000:3000
      - 8080:8080
    networks:
      - hc-network
    environment:
      - HOST=0.0.0.0
      - BACKEND_URL=http://backend:4000
      - MAPBOX_TOKEN="pk.eyJ1IjoiaHVtYW4tY29ubmVjdGlvbiIsImEiOiJjajl0cnBubGoweTVlM3VwZ2lzNTNud3ZtIn0.KZ8KK9l70omjXbEkkbHGsQ"

networks:
  hc-network:
    name: hc-network

volumes:
  node_modules:
