version: '3.7'

services:
  webapp:
    environment:
      - NODE_ENV=development
    build:
      context: .
      target: build-and-test
    volumes:
      - .:/nitro-web
      - node_modules:/nitro-web/node_modules
      - node_modules_styleguide:/nitro-web/styleguide/node_modules
    command: yarn run dev

volumes:
  node_modules:
  node_modules_styleguide:
