version: "3.7"

services:
  neo4j:
    environment:
      - NEO4J_AUTH=none
    ports:
      - 7687:7687
      - 7474:7474
  backend:
    ports:
      - 4001:4001
      - 4123:4123
    image: humanconnection/nitro-backend:builder
    build:
      context: .
      target: builder
