version: "3.7"

services:
  backend:
    container_name: backend.127.0.0.1.xip.io
    build: .
    networks:
      - hc-network
    depends_on:
      - neo4j
    ports:
      - 4000:4000
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - GRAPHQL_LISTEN_PORT=4000
      - GRAPHQL_URI=http://localhost:4000
      - CLIENT_URI=http://localhost:3000
      - JWT_SECRET=b/&&7b78BF&fv/Vd
      - MOCK=false

  neo4j:
    ports:
      - 7687:7687
      - 7474:7474
    build:
      context: .
      dockerfile: Dockerfile.neo4j
    networks:
      - hc-network
    volumes:
      - neo4j-data:/data
    environment:
      - NEO4J_AUTH=none

networks:
  hc-network:
    name: hc-network

volumes:
  neo4j-data:
