version: "3.4"

services:
  maintenance:
    image: humanconnection/maintenance-worker:latest
    build:
      context: maintenance
    volumes:
      - mongo-export:/mongo-export
      - uploads:/uploads
      - ./maintenance/migration/:/migration
      - ./maintenance/.ssh/:/root/.ssh/
      - neo4j-data:/data
    networks:
      - hc-network
    environment:
      - GRAPHQL_PORT=4000
      - GRAPHQL_URI=http://localhost:4000
      - CLIENT_URI=http://localhost:3000
      - JWT_SECRET=b/&&7b78BF&fv/Vd
      - MOCK=false
      - MAPBOX_TOKEN=pk.eyJ1IjoiaHVtYW4tY29ubmVjdGlvbiIsImEiOiJjajl0cnBubGoweTVlM3VwZ2lzNTNud3ZtIn0.KZ8KK9l70omjXbEkkbHGsQ
      - PRIVATE_KEY_PASSPHRASE=a7dsf78sadg87ad87sfagsadg78
      - NEO4J_URI=bolt://localhost:7687
      - "SSH_USERNAME=${SSH_USERNAME}"
      - "SSH_HOST=${SSH_HOST}"
      - "MONGODB_USERNAME=${MONGODB_USERNAME}"
      - "MONGODB_PASSWORD=${MONGODB_PASSWORD}"
      - "MONGODB_AUTH_DB=${MONGODB_AUTH_DB}"
      - "MONGODB_DATABASE=${MONGODB_DATABASE}"
      - "UPLOADS_DIRECTORY=${UPLOADS_DIRECTORY}"
      - NEO4J_AUTH=none
    ports:
      - 7687:7687
      - 7474:7474

volumes:
  mongo-export:
  uploads:
  neo4j-data:

networks:
  hc-network:
