apiVersion: v1
kind: Service
metadata:
  name:  {{ .Release.Name }}-webapp
spec:
  ports:
    - name: {{ .Release.Name }}-webapp
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    human-connection.org/selector: deployment-webapp
