apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Release.Name }}-webapp
spec:
  replicas: 2
  minReadySeconds: 15
  progressDeadlineSeconds: 60
  selector:
    matchLabels:
      human-connection.org/selector: deployment-webapp
  template:
    metadata:
      name: webapp
      labels:
        human-connection.org/commit: {{ .Values.commit }}
        human-connection.org/selector: deployment-webapp
    spec:
      containers:
      - name: webapp
        image: humanconnection/nitro-web:0.2.2
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-configmap
        - secretRef:
            name: {{ .Release.Name }}-secrets
        env:
        - name: HOST
          value: 0.0.0.0
        ports:
        - containerPort: 3000
        resources: {}
        imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
status: {}
