apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
      - env:
        - name: CLIENT_URI
          value: http://localhost:3000
        - name: GRAPHQL_PORT
          value: "4000"
        - name: GRAPHQL_URI
          value: http://localhost:4000
        - name: JWT_SECRET
          value: b/&&7b78BF&fv/Vd
        - name: MOCK
          value: "false"
        - name: NEO4J_URI
          value: bolt://neo4j:7687
        image: humanconnection/backend:latest
        name: backend
        ports:
        - containerPort: 4000
        resources: {}
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
status: {}
