apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: neo4j
  name: neo4j
spec:
  ports:
  - name: "7687"
    port: 7687
    targetPort: 7687
  - name: "7474"
    port: 7474
    targetPort: 7474
  selector:
    io.kompose.service: neo4j
status:
  loadBalancer: {}
