apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: human-connection
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/issuer: "letsencrypt-staging"
    certmanager.k8s.io/acme-challenge-type: http01
spec:
  tls:
  - hosts:
    - master.nitro.human-connection.org
    secretName: quickstart-example-tls
  rules:
  - host: master.nitro.human-connection.org
    http:
      paths:
      - path: /
        backend:
          serviceName: nitro-web
          servicePort: 3000
